import CatchAsyncError from "../utils/catchAsyncError.utils.js";

export const getContacts = CatchAsyncError(async (req, res, next) => {});

export const uploadContacts = CatchAsyncError(async (req, res, next) => {});

export const deleteContact = CatchAsyncError(async (req, res, next) => {});

export const modifyContact = CatchAsyncError(async (req, res, next) => {});
